import React from 'react';

const PrivacyPolicy = () => {
  return (
    <div className="container mx-auto p-6">
      {/* Header */}
      <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
      <p className="text-sm text-gray-500">Last updated: October 09, 2024</p>

      {/* Introduction */}
      <p className="mt-4">
        This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your
        information when You use the Service and tells You about Your privacy rights and how the law protects You.
      </p>
      <p>
        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection
        and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the
        help of the{' '}
        <a
          href="https://www.privacypolicies.com/privacy-policy-generator/"
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-500 underline"
        >
          Privacy Policy Generator
        </a>
        .
      </p>

      {/* Interpretation and Definitions */}
      <h2 className="text-2xl font-semibold mt-6 mb-2">Interpretation and Definitions</h2>

      {/* Interpretation */}
      <h3 className="text-xl font-semibold mt-4">Interpretation</h3>
      <p>
        The words of which the initial letter is capitalized have meanings defined under the following conditions. The
        following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </p>

      {/* Definitions */}
      <h3 className="text-xl font-semibold mt-4">Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul className="list-disc list-inside ml-6">
        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
        <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to MedCare.</li>
        <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device, or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
        <li><strong>Country</strong> refers to: Sri Lanka</li>
        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone, or a digital tablet.</li>
        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
        <li><strong>Service</strong> refers to the Website.</li>
        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li><strong>Website</strong> refers to MedCare, accessible from <a href="http://localhost:5173/" target="_blank" rel="noopener noreferrer" className="text-blue-500 underline">http://localhost:5173/</a></li>
        <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
      </ul>

      {/* Collecting and Using Your Personal Data */}
      <h2 className="text-2xl font-semibold mt-6 mb-2">Collecting and Using Your Personal Data</h2>

      {/* Types of Data Collected */}
      <h3 className="text-xl font-semibold mt-4">Types of Data Collected</h3>

      {/* Personal Data */}
      <h4 className="text-lg font-semibold mt-2">Personal Data</h4>
      <p>
        While using Our Service, We may ask You to provide Us with certain personally identifiable information that can
        be used to contact or identify You. Personally identifiable information may include, but is not limited to:
      </p>
      <ul className="list-disc list-inside ml-6">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
        <li>Usage Data</li>
      </ul>

      {/* Usage Data */}
      <h4 className="text-lg font-semibold mt-2">Usage Data</h4>
      <p>
        Usage Data is collected automatically when using the Service. Usage Data may include information such as Your
        Device's Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our Service
        that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers, and
        other diagnostic data.
      </p>

      {/* Tracking Technologies and Cookies */}
      <h4 className="text-lg font-semibold mt-2">Tracking Technologies and Cookies</h4>
      <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used include:</p>
      <ul className="list-disc list-inside ml-6">
        <li><strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.</li>
        <li><strong>Web Beacons:</strong> Small electronic files used to track the number of visitors or users interacting with specific pages or emails.</li>
      </ul>

      {/* Use of Your Personal Data */}
      <h3 className="text-xl font-semibold mt-4">Use of Your Personal Data</h3>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul className="list-disc list-inside ml-6">
        <li><strong>To provide and maintain our Service:</strong> Including monitoring the usage of our Service.</li>
        <li><strong>To manage Your Account:</strong> For managing registration as a user of the Service.</li>
        <li><strong>For the performance of a contract:</strong> Fulfilling contracts for products or services purchased through the Service.</li>
        <li><strong>To contact You:</strong> Communicating via email, phone, SMS, or push notifications.</li>
        <li><strong>For other purposes:</strong> Data analysis, marketing, service improvement, and more.</li>
      </ul>

      {/* Retention of Your Personal Data */}
      <h2 className="text-2xl font-semibold mt-6 mb-2">Retention of Your Personal Data</h2>
      <p>
        The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this
        Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with legal
        obligations, resolve disputes, and enforce legal agreements.
      </p>

      {/* Transfer of Your Personal Data */}
      <h2 className="text-2xl font-semibold mt-6 mb-2">Transfer of Your Personal Data</h2>
      <p>
        Your information, including Personal Data, may be transferred to and maintained on computers located outside of
        your jurisdiction. Your submission of such information represents your agreement to this transfer.
      </p>

      {/* Disclosure of Your Personal Data */}
      <h2 className="text-2xl font-semibold mt-6 mb-2">Disclosure of Your Personal Data</h2>
      <h3 className="text-xl font-semibold mt-4">Business Transactions</h3>
      <p>
        If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred. We
        will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
      </p>
      <h3 className="text-xl font-semibold mt-4"> Thank you! </h3>
    </div>
  );
};

export default PrivacyPolicy;
